config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?

  devise_for :users
  resources :tasks

  resources :topicos do # tarefas é um recurso de topicos
    resources :tasks, only: [:new]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #define root in homepage

  root to: "welcome#index"

  get "/developers", to: "developers#index"
  post "/developers", to: "developers#create_key"

  #get "/topicos", to: "topicos#index"
  #post "/topicos", to: "topicos#create"
  #get "/topicos/new", to: "topicos#new", as: :new_topico
  # get "/topicos/:id/edit", to: "topicos#edit", as: :edit_topico
  # get "/topicos/:id", to: "topicos#show", as: :topico
  # patch "/topicos/:id", to: "topicos#update"
  # put "/topicos/:id", to: "topicos#update"
  # delete "/topicos/:id", to: "topicos#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  scope :completas, -> { where(done: true) }
  scope :incompletas, -> { where(done: [false, nil]) }

  belongs_to :topico
  belongs_to :user
end

app/models/topico.rb
class Topico < ApplicationRecord
  has_many :tasks
  belongs_to :user

  #scope :topico_by_user, -> (current_id) {where("user_id = ?", current_id)}

  validates :titulo, length: { minimum: 3 }, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
  has_many :topicos

  def too_lazy?
    tasks.incompletas.count > 3
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate!
  layout :set_layout
  skip_before_action :verify_authenticity_token, if: -> {request.format.json? }

  private

  def set_layout
    current_user.present? ? "signed_in" : "application"
  end

  def authenticate!
    if request.format == Mime[:json]
      check_api_key
    else
      authenticate_user!
    end
  end

  def check_api_key
    user = authenticate_with_http_token { |t,_| User.find_by(api_key: t)}
    if user
      @current_user = user
    else
      render json: {erro: "Not authorized"}, status: :unauthorized
    end
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index
    @api_key = current_user.api_key
  end

  def create_key
    current_user.api_key = SecureRandom.alphanumeric(32)
    if current_user.save
      flash[:notice] = "Api key gerada com sucesso"
    else
      flash[:alert] = "Erro ao gerar API key"
    end

    redirect_to developers_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :show, :edit, :update, :destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = current_user.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @topicos = current_user.topicos.order(:titulo)

    @selected = params[:topico_id]
  end

  # GET /tasks/1/edit
  def edit
    @topicos = current_user.topicos.order(:titulo)
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if @task.save
        if current_user.too_lazy?
          UserMailer.with(user: current_user).too_lazy.deliver_later
          SearchGifJob.perform_later(@task)
        end
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html {
          @topicos = current_users.topicos
          render :new, status: :unprocessable_entity
        }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html {
          @topicos = current_users.topicos
          render :edit, status: :unprocessable_entity
        }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:titulo, :descricao, :vencimento, :done, :topico_id)
    end
end

app/controllers/topicos_controller.rb
class TopicosController < ApplicationController
  before_action :set_topico, only: [:show, :edit, :update, :destroy]

  def index
    @topicos = current_user.topicos
  end

  def show
  end

  def edit
  end

  def new
    @topico = Topico.new
  end

  def create
    @topico = Topico.new(topico_params)
    @topico.user = current_user
    if @topico.save
      redirect_to topico_url(@topico), notice: "Topico Criado"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @topico.update(topico_params)
      redirect_to topico_url(@topico), notice: "Topico Atualizado"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @topico.destroy
    redirect_to topicos_path, notice: "Topico removido"
  end

  private

  def set_topico
    @topico = Topico.find(params[:id])
  end

  def topico_params
    params.require(:topico).permit(:titulo)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate!
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/topicos_helper.rb
module TopicosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/developers/index.html.erb
<% if notice.present? %>
  <p style="color: green"><%= notice %></p>
<% end %>

<% if alert.present? %>
  <p style="color: red"><%= notice %></p>
<% end %>

<h1>Developers Dashboard</h1>

<% if @api_key.present? %>
  <p>Api key:<%= @api_key %></p>
<% end %>

<div>
  <%= button_to "Gerar API key" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield(:user_panel) if content_for(:user_panel) %>
    <%= yield %>
  </body>
</html>

app/views/layouts/signed_in.html.erb
<% content_for :user_panel do %>
  <div>
    <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete} %> |
    <%= link_to "Developers", developers_path %>
  </div>
<% end %>

<%= render template: "layouts/application" %>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.label :vencimento, style: "display: block" %>
    <%= form.date_select :vencimento %>
  </div>

  <div>
    <%= form.label :feito, style: "display: block" %>
    <%= form.check_box :done %>
  </div>

  <div>
    <%= form.label :topico, style: "display: block" %>
    <%= form.collection_select(:topico_id,
                               @topicos,
                               :id,
                               :titulo,
                               prompt: "Escolha um Tópico",
                               selected: @selected
        ) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Titulo:</strong>
    <%= task.titulo %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= task.descricao %>
  </p>

  <p>
    <strong>Vencimento:</strong>
    <%= task.vencimento %>
  </p>

  <p>
    <strong>Pronto:</strong>
    <%= task.done == true ? "Sim" : "Não" %>
  </p>

  <% if task.gif.present? %>
    <iframe src="<%= task.gif %>" width="380" height="280"></iframe>
  <% end %>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>

app/views/topicos/_form.html.erb
<%= form_with(model: topico) do |form| %>
  <% if topico.errors.any? %>
    <div style="color: red">
      <ul>
        <% topico.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.submit%>
  </div>
<% end %>

app/views/topicos/_topico.html.erb
<div id="<%= dom_id topico %>">
  <p>
    <strong>Titulo:</strong>
    <%= topico.titulo %>
  </p>

</div>

app/views/topicos/edit.html.erb
<%= render "form", topico: @topico %>

app/views/topicos/index.html.erb
<% if notice.present? %>
  <p style="color: green"><%= notice %></p>
<% end %>

<div>
  <% @topicos.each do |t| %>
    <%= render t, locals: {topico: t} %>
    <p><%= link_to "show topicos", t %></p>
  <% end %>
</div>

<%= link_to "novo tópico", new_topico_path %>

app/views/topicos/new.html.erb
<%= render "form", topico: @topico %>

<div>
  <%= link_to "topicos", topicos_path %>
</div>

app/views/topicos/show.html.erb
<% if notice.present? %>
  <p style="color: green"><%= notice %></p>
<% end %>

<%= render @topico %>

<div>
  <%= link_to "Topicos", topicos_path %>
  <%= link_to "Editar", edit_topico_path(@topico) %>

  <%= button_to "Remover Tópico", @topico, method: :delete %>

  <%= link_to "nova tarefa" ,new_topico_task_path(@topico) %>
</div>

app/views/welcome/index.html.erb
<h1>Hello world (chega mais)</h1>

<%= link_to "sign in", new_user_session_path, class: "btn btn-primary"%> |
<%= link_to "sign up", new_user_registration_path, class: "btn btn-primary" %>